# Generated by Django 5.2.8 on 2025-12-10 23:43

import private.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=private.models.avatar_upload_path),
        ),
    ]
