# Generated by Django 5.2.8 on 2025-12-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLauth', '0002_alter_captchamodel_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='captchamodel',
            options={'ordering': ['-create_time']},
        ),
        migrations.AlterField(
            model_name='captchamodel',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
